name: Deploy Fashion Recommender

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import app_simple; print('Flask app imports successfully')"
        python -c "import ast; ast.parse(open('main_simple.py').read()); print('Streamlit app syntax is valid')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug Secrets
      run: |
        echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
        echo "VPS_USERNAME: ${{ secrets.VPS_USERNAME }}"
        echo "VPS_PORT: ${{ secrets.VPS_PORT }}"
        echo "VPS_SSH_KEY length: ${#VPS_SSH_KEY}"
        if [ -z "${{ secrets.VPS_HOST }}" ]; then
          echo "ERROR: VPS_HOST is empty or not set"
          exit 1
        fi
        if [ -z "${{ secrets.VPS_USERNAME }}" ]; then
          echo "ERROR: VPS_USERNAME is empty or not set"
          exit 1
        fi
        if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
          echo "ERROR: VPS_SSH_KEY is empty or not set"
          exit 1
        fi
        echo "All secrets are properly set!"
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Navigate to project directory
          cd /opt/fashion-recommender
          
          # Pull latest changes
          git pull origin main
          
          # Stop existing containers
          docker-compose down
          
          # Remove old images
          docker image prune -f
          
          # Build and start new containers
          docker-compose up -d --build
          
          # Wait for services to be ready
          sleep 30
          
          # Check if services are running
          docker-compose ps
          
          # Test the application
          curl -f http://localhost:5001/health || exit 1
          
          echo "Deployment completed successfully!"
